### ISSUE TITLE
Clicking on run doesnt do anything

### ISSUE THREAD

**Issue by AcornGR** [Garten/sourcecraft#13]
after selecting the world, tf2 and the output directory and textures, when i pressed play it didnt do anything, just nothing. didnt put anything in the output folder too

**Comment by Garten** [comment]
Hm, sorry that the program doesn't communicate very much using the GUI yet. You may run the jar-file from the command-line. Then it should print quite some stuff giving us some insight. To do so, navigate to the folder containing the jar-file and run "java -jar sourcecraft-3.1.jar".

**Comment by AcornGR** [comment]
so yea i did that and it says this

> C:\Users\Capta\Documents\sourcecraft>java -jar sourcecraft-3.1.jar
(Minecraft.java:46)     valid minecraft path: C:\Users\Capta\AppData\Roaming\.minecraft
(Minecraft.java:100)    cannot create world
(Minecraft.java:100)    cannot create world
(Minecraft.java:100)    cannot create world
(Minecraft.java:100)    cannot create world
(Minecraft.java:100)    cannot create world
(Minecraft.java:100)    cannot create world
(Minecraft.java:100)    cannot create world
(Minecraft.java:100)    cannot create world
(Minecraft.java:100)    cannot create world
(Minecraft.java:100)    cannot create world
(Minecraft.java:100)    cannot create world
(Minecraft.java:100)    cannot create world
(Minecraft.java:100)    cannot create world
(Minecraft.java:100)    cannot create world
(Minecraft.java:100)    cannot create world
(Minecraft.java:100)    cannot create world
(Minecraft.java:100)    cannot create world
(Minecraft.java:100)    cannot create world
(Minecraft.java:100)    cannot create world
(Minecraft.java:100)    cannot create world
(SourceGame.java:69)    C:\Program Files (x86)\Steam\SteamApps\common\sourcesdk_content\tf\mapsrc
(GuiLogic.java:239)     changing output to C:\Program Files (x86)\Steam\SteamApps\common\sourcesdk_content\tf\mapsrc\test.vmf
(Steam.java:103)        checking textures in C:\Program Files (x86)\Steam\SteamApps\common\Team Fortress 2\tf\materials\minecraft_original
(Main.java:141)         world = ltn s4 new world
(Main.java:152)         option = default
(AddableManager.java:77)        adding Block
(AddableManager.java:77)        adding Cactus
(AddableManager.java:77)        adding Fence
(AddableManager.java:77)        adding Liquid
(AddableManager.java:77)        adding Pane
(AddableManager.java:77)        adding Slab
(AddableManager.java:77)        adding SnowBlock
(AddableManager.java:77)        adding StairsEast
(AddableManager.java:77)        adding StairsEast
(AddableManager.java:77)        adding StairsEast
(AddableManager.java:77)        adding StairsEast
(AddableManager.java:77)        adding StairsEast
(AddableManager.java:77)        adding StairsEast
(AddableManager.java:77)        adding ClipRampEast
(AddableManager.java:77)        adding StairsNorth
(AddableManager.java:77)        adding StairsNorth
(AddableManager.java:77)        adding StairsNorth
(AddableManager.java:77)        adding StairsNorth
(AddableManager.java:77)        adding ClipRampNorth
(AddableManager.java:77)        adding StairsSouth
(AddableManager.java:77)        adding StairsSouth
(AddableManager.java:77)        adding StairsSouth
(AddableManager.java:77)        adding StairsSouth
(AddableManager.java:77)        adding ClipRampSouth
(AddableManager.java:77)        adding StairsWest
(AddableManager.java:77)        adding StairsWest
(AddableManager.java:77)        adding StairsWest
(AddableManager.java:77)        adding StairsWest
(AddableManager.java:77)        adding StairsWest
(AddableManager.java:77)        adding ClipRampWest
(AddableManager.java:77)        adding TransparentBlock
(AddableManager.java:77)        adding EndPortalFrame
(AddableManager.java:77)        adding VinesEast
(AddableManager.java:77)        adding VinesNorth
(AddableManager.java:77)        adding VinesSouth
(AddableManager.java:77)        adding VinesWest
(AddableManager.java:77)        adding TorchNorth
(AddableManager.java:77)        adding TorchSouth
(AddableManager.java:77)        adding TorchEast
(AddableManager.java:77)        adding TorchWest
(AddableManager.java:77)        adding Torch
(AddableManager.java:77)        adding StairsHighEast
(AddableManager.java:77)        adding StairsHighEast
(AddableManager.java:77)        adding StairsHighEast
(AddableManager.java:77)        adding StairsHighEast
(AddableManager.java:77)        adding StairsHighEast
(AddableManager.java:77)        adding StairsHighEast
(AddableManager.java:77)        adding StairsHighEast
(AddableManager.java:77)        adding StairsHighEast
(AddableManager.java:77)        adding StairsHighNorth
(AddableManager.java:77)        adding StairsHighNorth
(AddableManager.java:77)        adding StairsHighNorth
(AddableManager.java:77)        adding StairsHighNorth
(AddableManager.java:77)        adding StairsHighNorth
(AddableManager.java:77)        adding StairsHighSouth
(AddableManager.java:77)        adding StairsHighSouth
(AddableManager.java:77)        adding StairsHighSouth
(AddableManager.java:77)        adding StairsHighSouth
(AddableManager.java:77)        adding StairsHighSouth
(AddableManager.java:77)        adding StairsHighWest
(AddableManager.java:77)        adding StairsHighWest
(AddableManager.java:77)        adding StairsHighWest
(AddableManager.java:77)        adding StairsHighWest
(AddableManager.java:77)        adding PlayerSpawnCss
(AddableManager.java:77)        adding PlayerSpawnCss
(AddableManager.java:77)        adding PlayerSpawnCss
(AddableManager.java:77)        adding PlayerSpawnCss
(AddableManager.java:77)        adding PlayerSpawnCss
(DefaultMinecraftMapConverter.java:278) from 65,19 to target 1 1
(DefaultMinecraftMapConverter.java:316) r.0.0.mca local [4 1] bounds [1 63 3] to [15 123 15] -> [1 1 1]
(DefaultMinecraftMapConverter.java:318) reading global chunk ( 4, 1) from C:\Users\Capta\AppData\Roaming\.minecraft\saves\ltn s4 new world\region\r.0.0.mca
java.io.EOFException
        at java.base/java.io.DataInputStream.readByte(DataInputStream.java:271)
        at minecraft.reader.nbt.NbtReader.readString(NbtReader.java:205)
        at minecraft.reader.nbt.NbtReader.readTitle(NbtReader.java:213)
        at minecraft.reader.nbt.NbtReader.doCompound(NbtReader.java:159)
        at minecraft.reader.nbt.McaReader.readSection(McaReader.java:72)
        at minecraft.reader.nbt.McaReader.lambda$readSections$1(McaReader.java:44)
        at minecraft.reader.nbt.McaReader$$Lambda$223/0x00000000df8ea3c8.run(Unknown Source)
        at minecraft.reader.nbt.NbtReader.doListOfCompounds(NbtReader.java:175)
        at minecraft.reader.nbt.McaReader.readSections(McaReader.java:43)
        at minecraft.reader.nbt.McaReader$$Lambda$222/0x00000000df8ea230.run(Unknown Source)
        at minecraft.reader.nbt.NbtReader.doCompound(NbtReader.java:164)
        at minecraft.reader.nbt.McaReader.lambda$readChunk$0(McaReader.java:37)
        at minecraft.reader.nbt.McaReader$$Lambda$221/0x00000000df8ea050.run(Unknown Source)
        at minecraft.reader.nbt.NbtReader.doCompound(NbtReader.java:164)
        at minecraft.reader.nbt.McaReader.readChunk(McaReader.java:36)
        at minecraft.map.DefaultMinecraftMapConverter.readChunk(DefaultMinecraftMapConverter.java:310)
        at minecraft.map.DefaultMinecraftMapConverter.open(DefaultMinecraftMapConverter.java:281)
        at main.Converter.getMinecraftMap(Converter.java:42)
        at main.Converter.convertMap(Converter.java:27)
        at main.Converter.convert(Converter.java:20)
        at main.Main.lambda$new$0(Main.java:60)
        at main.Main$$Lambda$217/0x00000000d5af5a28.run(Unknown Source)
        at gui.panel.DetailsPanel.lambda$initialize$2(DetailsPanel.java:135)
        at gui.panel.DetailsPanel$$Lambda$182/0x00000000d5aebdd8.actionPerformed(Unknown Source)
        at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
        at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
        at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
        at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
        at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
        at java.desktop/java.awt.Component.processMouseEvent(Component.java:6614)
        at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
        at java.desktop/java.awt.Component.processEvent(Component.java:6379)
        at java.desktop/java.awt.Container.processEvent(Container.java:2263)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4990)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4822)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4919)
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4548)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4489)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2769)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4822)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:704)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:704)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
(Converter.java:47)                     Did not find any mca-files.
(Converter.java:28)                     Saving to C:\Program Files (x86)\Steam\SteamApps\common\sourcesdk_content\tf\mapsrc\test.vmf
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at main.Converter.convertMap(Converter.java:30)
        at main.Converter.convert(Converter.java:20)
        at main.Main.lambda$new$0(Main.java:60)
        at main.Main$$Lambda$217/0x00000000d5af5a28.run(Unknown Source)
        at gui.panel.DetailsPanel.lambda$initialize$2(DetailsPanel.java:135)
        at gui.panel.DetailsPanel$$Lambda$182/0x00000000d5aebdd8.actionPerformed(Unknown Source)
        at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
        at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
        at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
        at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
        at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
        at java.desktop/java.awt.Component.processMouseEvent(Component.java:6614)
        at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
        at java.desktop/java.awt.Component.processEvent(Component.java:6379)
        at java.desktop/java.awt.Container.processEvent(Container.java:2263)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4990)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4822)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4919)
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4548)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4489)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2769)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4822)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:704)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:704)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
(OutputPanel.java:167)                  path: C:\Program Files (x86)\Steam\SteamApps\common\sourcesdk_content\tf\mapsrc\test.vmf
(GuiLogic.java:98)                      searching new output for C:\Program Files (x86)\Steam\SteamApps\common\sourcesdk_content\tf\mapsrc\test.vmf
(GuiLogic.java:103)                     C:\Users\Capta\Desktop\test.vmf
(Main.java:141)                         world = ltn s4 new world
(Main.java:152)                         option = default
(AddableManager.java:77)                adding Block
(AddableManager.java:77)                adding Cactus
(AddableManager.java:77)                adding Fence
(AddableManager.java:77)                adding Liquid
(AddableManager.java:77)                adding Pane
(AddableManager.java:77)                adding Slab
(AddableManager.java:77)                adding SnowBlock
(AddableManager.java:77)                adding StairsEast
(AddableManager.java:77)                adding StairsEast
(AddableManager.java:77)                adding StairsEast
(AddableManager.java:77)                adding StairsEast
(AddableManager.java:77)                adding StairsEast
(AddableManager.java:77)                adding StairsEast
(AddableManager.java:77)                adding ClipRampEast
(AddableManager.java:77)                adding StairsNorth
(AddableManager.java:77)                adding StairsNorth
(AddableManager.java:77)                adding StairsNorth
(AddableManager.java:77)                adding StairsNorth
(AddableManager.java:77)                adding ClipRampNorth
(AddableManager.java:77)                adding StairsSouth
(AddableManager.java:77)                adding StairsSouth
(AddableManager.java:77)                adding StairsSouth
(AddableManager.java:77)                adding StairsSouth
(AddableManager.java:77)                adding ClipRampSouth
(AddableManager.java:77)                adding StairsWest
(AddableManager.java:77)                adding StairsWest
(AddableManager.java:77)                adding StairsWest
(AddableManager.java:77)                adding StairsWest
(AddableManager.java:77)                adding StairsWest
(AddableManager.java:77)                adding ClipRampWest
(AddableManager.java:77)                adding TransparentBlock
(AddableManager.java:77)                adding EndPortalFrame
(AddableManager.java:77)                adding VinesEast
(AddableManager.java:77)                adding VinesNorth
(AddableManager.java:77)                adding VinesSouth
(AddableManager.java:77)                adding VinesWest
(AddableManager.java:77)                adding TorchNorth
(AddableManager.java:77)                adding TorchSouth
(AddableManager.java:77)                adding TorchEast
(AddableManager.java:77)                adding TorchWest
(AddableManager.java:77)                adding Torch
(AddableManager.java:77)                adding StairsHighEast
(AddableManager.java:77)                adding StairsHighEast
(AddableManager.java:77)                adding StairsHighEast
(AddableManager.java:77)                adding StairsHighEast
(AddableManager.java:77)                adding StairsHighEast
(AddableManager.java:77)                adding StairsHighEast
(AddableManager.java:77)                adding StairsHighEast
(AddableManager.java:77)                adding StairsHighEast
(AddableManager.java:77)                adding StairsHighNorth
(AddableManager.java:77)                adding StairsHighNorth
(AddableManager.java:77)                adding StairsHighNorth
(AddableManager.java:77)                adding StairsHighNorth
(AddableManager.java:77)                adding StairsHighNorth
(AddableManager.java:77)                adding StairsHighSouth
(AddableManager.java:77)                adding StairsHighSouth
(AddableManager.java:77)                adding StairsHighSouth
(AddableManager.java:77)                adding StairsHighSouth
(AddableManager.java:77)                adding StairsHighSouth
(AddableManager.java:77)                adding StairsHighWest
(AddableManager.java:77)                adding StairsHighWest
(AddableManager.java:77)                adding StairsHighWest
(AddableManager.java:77)                adding StairsHighWest
(AddableManager.java:77)                adding PlayerSpawnCss
(AddableManager.java:77)                adding PlayerSpawnCss
(AddableManager.java:77)                adding PlayerSpawnCss
(AddableManager.java:77)                adding PlayerSpawnCss
(AddableManager.java:77)                adding PlayerSpawnCss
(DefaultMinecraftMapConverter.java:278) from 65,19 to target 1 1
(DefaultMinecraftMapConverter.java:316) r.0.0.mca local [4 1] bounds [1 63 3] to [15 123 15] -> [1 1 1]
(DefaultMinecraftMapConverter.java:318) reading global chunk ( 4, 1) from C:\Users\Capta\AppData\Roaming\.minecraft\saves\ltn s4 new world\region\r.0.0.mca
java.io.EOFException
        at java.base/java.io.DataInputStream.readByte(DataInputStream.java:271)
        at minecraft.reader.nbt.NbtReader.readString(NbtReader.java:205)
        at minecraft.reader.nbt.NbtReader.readTitle(NbtReader.java:213)
        at minecraft.reader.nbt.NbtReader.doCompound(NbtReader.java:159)
        at minecraft.reader.nbt.McaReader.readSection(McaReader.java:72)
        at minecraft.reader.nbt.McaReader.lambda$readSections$1(McaReader.java:44)
        at minecraft.reader.nbt.McaReader$$Lambda$223/0x00000000df8ea3c8.run(Unknown Source)
        at minecraft.reader.nbt.NbtReader.doListOfCompounds(NbtReader.java:175)
        at minecraft.reader.nbt.McaReader.readSections(McaReader.java:43)
        at minecraft.reader.nbt.McaReader$$Lambda$222/0x00000000df8ea230.run(Unknown Source)
        at minecraft.reader.nbt.NbtReader.doCompound(NbtReader.java:164)
        at minecraft.reader.nbt.McaReader.lambda$readChunk$0(McaReader.java:37)
        at minecraft.reader.nbt.McaReader$$Lambda$221/0x00000000df8ea050.run(Unknown Source)
        at minecraft.reader.nbt.NbtReader.doCompound(NbtReader.java:164)
        at minecraft.reader.nbt.McaReader.readChunk(McaReader.java:36)
        at minecraft.map.DefaultMinecraftMapConverter.readChunk(DefaultMinecraftMapConverter.java:310)
        at minecraft.map.DefaultMinecraftMapConverter.open(DefaultMinecraftMapConverter.java:281)
        at main.Converter.getMinecraftMap(Converter.java:42)
        at main.Converter.convertMap(Converter.java:27)
        at main.Converter.convert(Converter.java:20)
        at main.Main.lambda$new$0(Main.java:60)
        at main.Main$$Lambda$217/0x00000000d5af5a28.run(Unknown Source)
        at gui.panel.DetailsPanel.lambda$initialize$2(DetailsPanel.java:135)
        at gui.panel.DetailsPanel$$Lambda$182/0x00000000d5aebdd8.actionPerformed(Unknown Source)
        at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
        at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
        at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
        at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
        at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
        at java.desktop/java.awt.Component.processMouseEvent(Component.java:6614)
        at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
        at java.desktop/java.awt.Component.processEvent(Component.java:6379)
        at java.desktop/java.awt.Container.processEvent(Container.java:2263)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4990)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4822)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4919)
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4548)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4489)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2769)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4822)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:704)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:704)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
(Converter.java:47)                     Did not find any mca-files.
(Converter.java:28)                     Saving to C:\Users\Capta\Desktop\test.vmf
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at main.Converter.convertMap(Converter.java:30)
        at main.Converter.convert(Converter.java:20)
        at main.Main.lambda$new$0(Main.java:60)
        at main.Main$$Lambda$217/0x00000000d5af5a28.run(Unknown Source)
        at gui.panel.DetailsPanel.lambda$initialize$2(DetailsPanel.java:135)
        at gui.panel.DetailsPanel$$Lambda$182/0x00000000d5aebdd8.actionPerformed(Unknown Source)
        at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
        at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
        at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
        at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
        at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
        at java.desktop/java.awt.Component.processMouseEvent(Component.java:6614)
        at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
        at java.desktop/java.awt.Component.processEvent(Component.java:6379)
        at java.desktop/java.awt.Container.processEvent(Container.java:2263)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4990)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4822)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4919)
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4548)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4489)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2769)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4822)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:704)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:704)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by Netskytten** [comment]
I have the same problem. The "run" button doesn't do anything.
